#!/usr/bin/env bash
IPT="/usr/sbin/iptables-legacy"
IPT6="/usr/sbin/ip6tables-legacy"
IPSET4="blocklist"
IPSET6="blocklist6"

# Flush and destroy ipsets
ipset flush $IPSET4
ipset flush $IPSET6
ipset destroy $IPSET4
ipset destroy $IPSET6

# Remove OUTPUT rules
$IPT -D OUTPUT -m set --match-set $IPSET4 dst -j DROP 2>/dev/null || true
$IPT6 -D OUTPUT -m set --match-set $IPSET6 dst -j DROP 2>/dev/null || true

echo "Netsentinel cleanup done"

